"""add completed_challenges

Revision ID: 5632942f4e4e
Revises: 
Create Date: 2026-06-25 19:55:32.342436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5632942f4e4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_challenges', sa.JSON(), nullable=True))
        batch_op.drop_column('compledted_challs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compledted_challs', sqlite.JSON(), nullable=True))
        batch_op.drop_column('completed_challenges')

    # ### end Alembic commands ###
